version: "3.8"
services:
  web:
    container_name: php-apache
    image: php:8.0-apache
    depends_on: 
    - mysql
    volumes: 
    - ./:/var/www/html/
    ports:
    - 80:80
    build: .
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: dockerexample
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8081:80
    environment: 
      PMA_HOST: mysql #mysql container name
      PMA_PORT: 3306
volumes:
  dbdata: